Update reference-documents.csv
buildingSMART/bSDD pull request #117
Opened 2024-12-19 08:16 UTC by atomczak

2024-12-19 13:24 UTC, Erik-RN requested changes

2024-12-19 13:24 UTC, Erik-RN commented on DataFiles/reference-documents.csv
> +European Illustrated Glossary of Conservation Terms for Wall Paintings and Architectural Surfaces,2015-01-01,EwaGlos – European Illustrated Glossary of Conservation Terms for Wall Paintings and Archi
"European Illustrated Glossary of Conservation Terms for Wall Paintings and Architectural Surfaces" is not a code and it's too long. Now it is the same as the description. Suggestion: EIGCTWPAS-2015.
Codes are meant for efficient digital communication, not to be human readable :-)

2024-12-19 13:24 UTC, Erik-RN commented on DataFiles/reference-documents.csv
> +Illustrated Glossary on Stone Deterioration Patterns,2008-09-01,Illustrated Glossary on Stone Deterioration Patterns
Same here, the code is not a code and it is too long (max 50 chars).
Suggestion: IGSDP-2008

2024-12-31 13:20 UTC, Baars-IT approved these changes

2024-12-31 13:21 UTC, merged